#if !canImport(ObjectiveC)
import XCTest

extension GherkinFeatureTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GherkinFeatureTests = [
        ("testFeatureShouldFailIfScenarioOutlineHasNoExamples", testFeatureShouldFailIfScenarioOutlineHasNoExamples),
        ("testScenarioBadRegex", testScenarioBadRegex),
        ("testScenarioShouldBeCaseInsensitive", testScenarioShouldBeCaseInsensitive),
        ("testScenarioShouldExist", testScenarioShouldExist),
        ("testScenarioShouldNotExist", testScenarioShouldNotExist),
    ]
}

extension GherkinGivenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GherkinGivenTests = [
        ("testGivenMethodShouldFindSpecificRegex", testGivenMethodShouldFindSpecificRegex),
    ]
}

extension GherkinLoadFeatureTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GherkinLoadFeatureTests = [
        ("testLoadShouldFailWhenFeaturePathIsNotCorrect", testLoadShouldFailWhenFeaturePathIsNotCorrect),
        ("testLoadShouldSucceed", testLoadShouldSucceed),
    ]
}

extension GherkinScenarioTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GherkinScenarioTests = [
        ("testScenarioOutlineHasName", testScenarioOutlineHasName),
        ("testSimpleScenarioHasNoExamples", testSimpleScenarioHasNoExamples),
        ("testStepBadRegex", testStepBadRegex),
        ("testStepShouldBeCaseInsensitive", testStepShouldBeCaseInsensitive),
        ("testStepShouldExist", testStepShouldExist),
        ("testStepShouldNotExist", testStepShouldNotExist),
    ]
}

extension GherkinSearchErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GherkinSearchErrorTests = [
        ("testEquatable", testEquatable),
        ("testNotEquatable", testNotEquatable),
    ]
}

extension SwiftGherkinTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftGherkinTests = [
        ("testCreatingAFeatureInCode", testCreatingAFeatureInCode),
        ("testParsingFeatureFileWithDescription", testParsingFeatureFileWithDescription),
        ("testParsingFeatureFileWithMultiLineDescription", testParsingFeatureFileWithMultiLineDescription),
        ("testParsingFeatureFileWithMultipleScenarios", testParsingFeatureFileWithMultipleScenarios),
        ("testParsingFeatureFileWithScenarioDescription", testParsingFeatureFileWithScenarioDescription),
        ("testParsingSimpleFeatureFile", testParsingSimpleFeatureFile),
        ("testParsingSimpleFeatureFileWithIndentation", testParsingSimpleFeatureFileWithIndentation),
        ("testParsingSimpleFeatureFileWithMultipleTags", testParsingSimpleFeatureFileWithMultipleTags),
        ("testParsingSimpleFeatureFileWithMultipleTagsBeforeFeature", testParsingSimpleFeatureFileWithMultipleTagsBeforeFeature),
        ("testParsingSimpleFeatureFileWithMultipleVariable", testParsingSimpleFeatureFileWithMultipleVariable),
        ("testParsingSimpleFeatureFileWithMultipleVariableAndTag", testParsingSimpleFeatureFileWithMultipleVariableAndTag),
        ("testParsingSimpleFeatureFileWithMultipleVariableAndTagBeforeFeature", testParsingSimpleFeatureFileWithMultipleVariableAndTagBeforeFeature),
        ("testParsingSimpleFeatureFileWithMultipleVariableAndTags", testParsingSimpleFeatureFileWithMultipleVariableAndTags),
        ("testParsingSimpleFeatureFileWithMultipleVariableAndTagsBeforeFeature", testParsingSimpleFeatureFileWithMultipleVariableAndTagsBeforeFeature),
        ("testParsingSimpleFeatureFileWithTag", testParsingSimpleFeatureFileWithTag),
        ("testParsingSimpleFeatureFileWithTagBeforeFeature", testParsingSimpleFeatureFileWithTagBeforeFeature),
        ("testParsingSimpleFeatureFileWithTagsBeforeFeatureAndBeforeScenario", testParsingSimpleFeatureFileWithTagsBeforeFeatureAndBeforeScenario),
        ("testParsingSimpleFeatureFileWithVariable", testParsingSimpleFeatureFileWithVariable),
        ("testParsingSimpleFeatureFileWithVariableWithIndentation", testParsingSimpleFeatureFileWithVariableWithIndentation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GherkinFeatureTests.__allTests__GherkinFeatureTests),
        testCase(GherkinGivenTests.__allTests__GherkinGivenTests),
        testCase(GherkinLoadFeatureTests.__allTests__GherkinLoadFeatureTests),
        testCase(GherkinScenarioTests.__allTests__GherkinScenarioTests),
        testCase(GherkinSearchErrorTests.__allTests__GherkinSearchErrorTests),
        testCase(SwiftGherkinTests.__allTests__SwiftGherkinTests),
    ]
}
#endif
